### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by cory-baker** [learn-co-students/python-practice-with-datatypes-data-science-pilot#1]
first section, second paragraph, first sentence reads "In this lesson we'll imagine that just met Art Vandelay, a CEO of his own travel agency, Vandelay Industries."

should probably read: "In this lesson we'll imagine that WE just met Art Vandelay, a CEO of his own travel agency, Vandelay Industries."

addition of "we"

**Comment by tkoar** [comment]
This has been reworded and will be merged in. Thanks!
