### ISSUE TITLE
Infinite container loading

### ISSUE THREAD

**Issue by yoyothesheep** [learn-co-students/python-practice-with-datatypes-data-science-pilot#10]
At least 2 students reported the loading icon hangs for several minutes. 

TODO - check if they ever load the notebook. See if it's laptop specific.

**Comment by talum** [comment]
This is likely more an engineering issue than a curriculum one, so I think we should close this here and I'll open a ticket on our end. I gathered some screenshots from the pilot that should help with debugging.
