### ISSUE TITLE
On reload it loses your notebook progress

### ISSUE THREAD

**Issue by walkingalchemy** [learn-co-students/python-practice-with-datatypes-data-science-pilot#7]
All changes made to the code in the notebook is gone.

**Comment by yoyothesheep** [comment]
1. I think we're supposed to be auto-saving so maybe that didn't happen.

2. I thought this is a "Jupyter readme" which means this shouldn't be interactive? Tracy am I understanding that wrong? Are readme's interactive but just no tests?

**Comment by talum** [comment]
I believe this is resolved. We didn't have the correct autosave interval in.

Jupyter readmes are interactive without tests.
