### ISSUE TITLE
There's a solution branch for this readme? 

### ISSUE THREAD

**Issue by yoyothesheep** [learn-co-students/python-practice-with-datatypes-data-science-pilot#8]
https://github.com/learn-co-students/python-practice-with-datatypes-data-science-pilot/tree/solution

FYI having a solution directory triggers the UI attached

<img width="232" alt="screen shot 2018-03-14 at 3 03 29 pm" src="https://user-images.githubusercontent.com/33908481/37425724-c001a25e-279a-11e8-9b20-c4834377e4c8.png">

**Comment by tkoar** [comment]
This lesson has been configured to be a lab and will now show as one in learn.
