### ISSUE TITLE
Stops loading jupyter notebook on reload

### ISSUE THREAD

**Issue by walkingalchemy** [learn-co-students/python-practice-with-datatypes-data-science-pilot#9]
Originally it was displaying but it now flashes the readme.md then loads the ipython, then displays a blank screen.

**Comment by yoyothesheep** [comment]
https://cl.ly/291e470N172m

**Comment by yoyothesheep** [comment]
This actually maybe an "unsecure content" issue again. Try to load unsecure content?

**Comment by talum** [comment]
Yes, this is SSL.
